language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  pip install coveralls

env:
  global:
  - TRAVIS="True"

script: ./script/test

after_success:
  coveralls

notifications:
  email: false
